### ISSUE TITLE
Reader.readの返り値にはそのreadで読み取ったものを返してほしい

### ISSUE THREAD

**Issue by sidepelican** [omochi/SwiftTypeReader#18]
現在の`Reader.read`は `Module`を返しているが、これは`Reader`のプロパティにそのまま生えてる`module`と同一であり、情報としては嬉しくない。
その1回の`read`で読み取った型などのセットを返してあげると、使う側でファイルやディレクトリ単位で読み込まれたものを管理できて便利だと思いました。

**Comment by omochi** [comment]
`SourceFile` を導入して `read` はそれを返すようにしようと思います。

**Comment by omochi** [comment]
@sidepelican 

↓以下のパッチでうまく要望が解決できるか試してもらえますか？
https://github.com/omochi/SwiftTypeReader/pull/19

**Comment by omochi** [comment]
`1.1.5` で対応してリリースしました。
