### ISSUE TITLE
ErrorTypeの命名がややこしい

### ISSUE THREAD

**Issue by sidepelican** [omochi/SwiftTypeReader#44]
`ErrorType` はシンボル解決に失敗した型を表していると思いますが、Swiftには`Error`という特殊な型が存在するのでそちらと混同してややこしいと感じました。

- `ErroredType`
- `UnresolvableType`
- `UnknownType`

などの命名に変更するのはどうでしょうか

**Comment by omochi** [comment]
`ErrorType` は、汎用的に `Type` を用意しようとして何らかの不正な入力や実装のバグによってそれが失敗した場合に、
例外を投げる代わりに、失敗したことを表す型として使っているものです。

例外を投げないようにしているのは、
ソースコード入力においてそういう部分があっても、
他の部分は処理できるかもしれないので、
問題はその場に残しておいて処理は進行したいからです。

つまり、汎用的な失敗を表しているので、
Error というワードが一番自然です。

シンボル解決に失敗するのはメジャーな用途の一つではありますが、
この型の意味はもっと広くて、
シンボル解決はあくまで失敗の一つでしかないという位置づけです。
`public var repr: (any TypeRepr)?` がオプショナルなのもそれが理由です。

UnresolvableやUnknownは特定の失敗状況を表すワードなので、
変更先としては不適切です。

その点Erroredは良さそうですが、
ここで受け身系を使うルールを入れると、
他の場合でも受け身を使うべきか気にする必要が出てくるのが負担に感じます。
あまり意味も変わっていないので、
`ErrorType` と `ErroredType` の2つがあったとき問題が解決しているかというと微妙だと思います。
結果としての値という意味が表現できている気もしますが・・・

また、 `Swift.Error` についてはSwiftでは単なるprotocolなので、
まずは `SwiftTypeReader.ProtocolType` に属しますし、
特別に区別するとしたら `SwiftTypeReader.ErrorProtocolType` となりそうです。
このライブラリの設計だと `Swift.Error` は直接出てくる粒度の概念ではなさそう。

このようなエラーの値を保持するケースをSwiftで考えてみると、
やはりそのまま `var error: Error?` で表現するのが一番標準的で、
語としてはerrorになると思います。

もう一つは `Swift.Result` が似たような役割を持っていて、
こちらの場合は失敗には failure という言葉を当てているので、
`SwiftTypeReader.FailureType` は候補かもしれません。

全体としては、
ややこしいのはわかるけどこのライブラリにおいてはここはこの名前が一番ベストだから、
気をつけてもらうしかないかなあと思います。

**Comment by sidepelican** [comment]
`Error` は protocolでありながら唯一ジェネリックパラメータとして利用できるため、その特別処理のためにSwiftTypeReader内で専用の型が用意されることもあるかと想像していました。

> ErrorType と ErroredType の2つがあったとき問題が解決しているかというと微妙

これはそうですね・・。2つ同時に存在したら結局煩雑なのは変わらない。

シンボル解決以外のエラーも表したいという旨は了解しました。

`FailureType`は良さそうですが、一旦はややこしいけど気をつけて使うことにします

**Comment by sidepelican** [comment]
ライブラリの内部エラーとシンボル解決の失敗を区別できていないという別の問題はあるかも。
それを区別できればエラー状態の型付けの意味合いが生まれるので`UnresolvableType`の意義が生まれる。
